sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_a1a7c43a548d_key -iv $encrypted_a1a7c43a548d_iv -in multi-k8s-289412-d76db18e0fa8.json.enc -out multi-k8s-289412-d76db18e0fa8.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-289412-d76db18e0fa8.json
  - gcloud config set project multi-k8s-289412
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin